-- =============================================================================
-- Custom migration: triggers, functions, partial index, check constraint
-- This file is NOT auto-regenerated by drizzle-kit — edit by hand.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Generic set_updated_at() function — reused by multiple triggers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tasks_updated_at
  BEFORE UPDATE ON tasks
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_goals_updated_at
  BEFORE UPDATE ON goals
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_scheduled_blocks_updated_at
  BEFORE UPDATE ON scheduled_blocks
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 2. update_goal_counters — maintains goals.total_tasks / completed_tasks
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_goal_counters()
RETURNS TRIGGER AS $$
DECLARE
  affected_goal_id BIGINT;
BEGIN
  -- Handle goal_id change: update the OLD goal first
  IF TG_OP = 'UPDATE' AND OLD.goal_id IS DISTINCT FROM NEW.goal_id THEN
    UPDATE goals SET
      total_tasks     = (SELECT count(*) FROM tasks WHERE goal_id = OLD.goal_id),
      completed_tasks = (SELECT count(*) FROM tasks WHERE goal_id = OLD.goal_id AND status = 'completed')
    WHERE id = OLD.goal_id;
    affected_goal_id := NEW.goal_id;
  ELSIF TG_OP = 'DELETE' THEN
    affected_goal_id := OLD.goal_id;
  ELSE
    affected_goal_id := COALESCE(NEW.goal_id, OLD.goal_id);
  END IF;

  UPDATE goals SET
    total_tasks     = (SELECT count(*) FROM tasks WHERE goal_id = affected_goal_id),
    completed_tasks = (SELECT count(*) FROM tasks WHERE goal_id = affected_goal_id AND status = 'completed')
  WHERE id = affected_goal_id;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_goal_counters
  AFTER INSERT OR UPDATE OF status, goal_id OR DELETE
  ON tasks
  FOR EACH ROW
  EXECUTE FUNCTION update_goal_counters();

-- ---------------------------------------------------------------------------
-- 3. update_blocker_counts — adjusts tasks.blocker_count on dependency edges
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_blocker_counts()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- Only increment if the prerequisite is NOT already completed
    IF (SELECT status FROM tasks WHERE id = NEW.depends_on_id) <> 'completed' THEN
      UPDATE tasks SET blocker_count = blocker_count + 1 WHERE id = NEW.task_id;
    END IF;
  ELSIF TG_OP = 'DELETE' THEN
    -- Only decrement if the prerequisite was NOT completed
    IF (SELECT status FROM tasks WHERE id = OLD.depends_on_id) <> 'completed' THEN
      UPDATE tasks SET blocker_count = GREATEST(blocker_count - 1, 0) WHERE id = OLD.task_id;
    END IF;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_blocker_counts
  AFTER INSERT OR DELETE
  ON task_dependencies
  FOR EACH ROW
  EXECUTE FUNCTION update_blocker_counts();

-- ---------------------------------------------------------------------------
-- 4. cascade_blocker_count — when a task completes/uncompletes, update dependents
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION cascade_blocker_count()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'completed' AND OLD.status <> 'completed' THEN
    -- Task just completed: decrement blocker_count for all dependents
    UPDATE tasks SET blocker_count = GREATEST(blocker_count - 1, 0)
    WHERE id IN (
      SELECT task_id FROM task_dependencies WHERE depends_on_id = NEW.id
    );
  ELSIF OLD.status = 'completed' AND NEW.status <> 'completed' THEN
    -- Task un-completed: re-increment blocker_count for all dependents
    UPDATE tasks SET blocker_count = blocker_count + 1
    WHERE id IN (
      SELECT task_id FROM task_dependencies WHERE depends_on_id = NEW.id
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_cascade_blocker_count
  AFTER UPDATE OF status
  ON tasks
  FOR EACH ROW
  EXECUTE FUNCTION cascade_blocker_count();

-- ---------------------------------------------------------------------------
-- 5. prevent_cycle — BEFORE INSERT on task_dependencies, detect cycles via CTE
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION prevent_cycle()
RETURNS TRIGGER AS $$
BEGIN
  -- Prevent self-references
  IF NEW.task_id = NEW.depends_on_id THEN
    RAISE EXCEPTION 'cycle detected: task % cannot depend on itself', NEW.task_id
      USING ERRCODE = 'check_violation';
  END IF;

  -- Check if adding this edge would create a cycle:
  -- Walk forward from NEW.task_id through existing edges. If we reach
  -- NEW.depends_on_id, there would be a cycle.
  IF EXISTS (
    WITH RECURSIVE reachable AS (
      SELECT td.task_id AS node
      FROM task_dependencies td
      WHERE td.depends_on_id = NEW.task_id
      UNION ALL
      SELECT td.task_id
      FROM task_dependencies td
      JOIN reachable r ON td.depends_on_id = r.node
    )
    SELECT 1 FROM reachable WHERE node = NEW.depends_on_id
  ) THEN
    RAISE EXCEPTION 'cycle detected: task % cannot depend on %', NEW.task_id, NEW.depends_on_id
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_prevent_cycle
  BEFORE INSERT OR UPDATE
  ON task_dependencies
  FOR EACH ROW
  EXECUTE FUNCTION prevent_cycle();

-- ---------------------------------------------------------------------------
-- 6. Check constraint: no self-dependencies
-- ---------------------------------------------------------------------------
ALTER TABLE task_dependencies ADD CONSTRAINT chk_no_self_dep
  CHECK (task_id <> depends_on_id);

-- ---------------------------------------------------------------------------
-- 7. Partial index for ready tasks (hot path)
-- ---------------------------------------------------------------------------
CREATE INDEX idx_tasks_ready
  ON tasks (user_id)
  WHERE blocker_count = 0 AND status = 'pending';

-- ---------------------------------------------------------------------------
-- 8. reconcile_counters() — repair function for drifted denormalized counters
-- Schedule via pg_cron: SELECT reconcile_counters();
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION reconcile_counters()
RETURNS void AS $$
BEGIN
  -- Fix goal counters
  UPDATE goals g SET
    total_tasks = sub.total,
    completed_tasks = sub.completed
  FROM (
    SELECT goal_id,
           count(*)::int AS total,
           (count(*) FILTER (WHERE status = 'completed'))::int AS completed
    FROM tasks
    GROUP BY goal_id
  ) sub
  WHERE g.id = sub.goal_id
    AND (g.total_tasks IS DISTINCT FROM sub.total
      OR g.completed_tasks IS DISTINCT FROM sub.completed);

  -- Fix blocker counts
  UPDATE tasks t SET
    blocker_count = COALESCE(sub.cnt, 0)
  FROM (
    SELECT td.task_id,
           (count(*) FILTER (WHERE dep.status <> 'completed'))::int AS cnt
    FROM task_dependencies td
    JOIN tasks dep ON dep.id = td.depends_on_id
    GROUP BY td.task_id
  ) sub
  WHERE t.id = sub.task_id
    AND t.blocker_count IS DISTINCT FROM sub.cnt;

  -- Tasks with no dependencies should have blocker_count = 0
  UPDATE tasks SET blocker_count = 0
  WHERE blocker_count <> 0
    AND id NOT IN (SELECT task_id FROM task_dependencies);
END;
$$ LANGUAGE plpgsql;
